language: python
dist: focal
python:
    - nightly
    - 3.10
    - 3.9
    - 3.8
    - 3.7
    - 3.6
    - 3.5
    - 2.7
before_install:
  - pip install poetry
install:
  - poetry build
env:
  - CYTHON_DEBUG=1
script:
  - poetry run pytest
after_success: coveralls
