language: python
dist: bionic
python:
    - nightly
    - 3.10
    - 3.9
    - 3.8
    - 3.7
    - 3.6
    - 3.5
    - 2.7
install:
  #- pip install -r requirements.txt
  - curl -sSL https://install.python-poetry.org | python -
  # https://github.com/pypa/setuptools/issues/3293
  #- pip install --upgrade importlib-metadata
  #- pip install .
  - python setup.py develop
  - pip install nose coveralls
env:
  - CYTHON_DEBUG=1
script: coverage run --source=zigzag setup.py nosetests
after_success: coveralls
