[tool.poetry]
name = "zigzag"
version = "0.3.0"
description = "Package for finding peaks and valleys of time series."
authors = ["generativist <jbn@abreka.com>"]
license = "BSD-3-Clause"
packages = [{ include = "zigzag" }]
include = [{ path = "zigzag/**/*.so", format = "wheel" }]

[tool.poetry.dependencies]
python = "^2.7"
numpy = "^1.23.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "Cython",
]
build-backend = "poetry.core.masonry.api"
