[build-system]
requires = [
    "poetry-core>=1.0.0",
    "Cython~=0.29.6",
    "numpy=^1.23.1",
    "distutils",
]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "zigzag"
version = "0.3.0"
description = "Package for finding peaks and valleys of time series."
authors = ["generativist <jbn@abreka.com>"]
license = "BSD-3-Clause"
packages = [{ include = "zigzag" }]
include = [{ path = "zigzag/**/*.so", format = "wheel" }]

[tool.poetry.dependencies]
python = ">2.7"
numpy = "^1.0.1"

[tool.poetry.build]
generate-setup-file = false
script = "build.py"


[tool.poetry.dev-dependencies]
pytest = "^5.0"
Cython = "^0.29.0"